<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>Library</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspose.Cells" Version="24.11.0" />
		<PackageReference Include="EPPlus" Version="7.5.0" />
		<PackageReference Include="itext7" Version="8.0.5" />
		<PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1001" />
		<PackageReference Include="MongoDB.Bson" Version="3.0.0" />
		<PackageReference Include="MongoDB.Driver" Version="3.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

</Project>