<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU;x86</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Agencia.cs" />
		<Compile Remove="Agencias.cs" />
		<Compile Remove="Capa.cs" />
		<Compile Remove="FinanceiroModels.cs" />
		<Compile Remove="IEntidadeBase.cs" />
		<Compile Remove="LicencaImportacao.cs" />
		<Compile Remove="Logado.cs" />
		<Compile Remove="LpcoInfo.cs" />
		<Compile Remove="LpcoViewModel.cs" />
		<Compile Remove="NotificacaoService.cs" />
		<Compile Remove="NotifUrgente.cs" />
		<Compile Remove="OrgaoAnuente.cs" />
		<Compile Remove="Recibo.cs" />
		<Compile Remove="RepositorioFatura.cs" />
		<Compile Remove="RepositorioNotificacao.cs" />
		<Compile Remove="RepositorioOrgaoAnuente.cs" />
		<Compile Remove="RepositorioRecibo.cs" />
		<Compile Remove="RepositorioUsers.cs" />
		<Compile Remove="RepositorioVistorias.cs" />
		<Compile Remove="Users.cs" />
		<Compile Remove="Vistoria.cs" />
		<Compile Remove="VistoriaService.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Aspose.Cells" Version="24.11.0" />
		<PackageReference Include="EPPlus" Version="7.5.0" />
		<PackageReference Include="itext7" Version="8.0.5" />
		<PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1001" />
		<PackageReference Include="MongoDB.Bson" Version="3.0.0" />
		<PackageReference Include="MongoDB.Driver" Version="3.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

</Project>