<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>Library</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspose.Cells" Version="25.12.0" />
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="EPPlus" Version="8.4.0" />
		<PackageReference Include="itext" Version="9.4.0" />
		<PackageReference Include="Microsoft.Office.Interop.Excel" Version="16.0.18925.20022" />
		<PackageReference Include="MongoDB.Bson" Version="3.5.2" />
		<PackageReference Include="MongoDB.Driver" Version="3.5.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

</Project>